# Generated by Django 5.2.4 on 2026-03-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='e.g. S, M, L, XL, 42, 256GB', max_length=50)),
                ('color', models.CharField(blank=True, help_text='e.g. Red, Blue, Black', max_length=50)),
                ('color_hex', models.CharField(blank=True, help_text='Hex code e.g. #FF0000', max_length=7)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Amount added to/subtracted from base price. e.g. 50 means +$50', max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku_suffix', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'ordering': ['size', 'color'],
            },
        ),
    ]
