# Generated by Django 5.2.4 on 2026-03-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_faq_models_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_demo',
            field=models.FileField(blank=True, help_text='Short demo clip (mp4/webm). Auto-plays muted on hover.', null=True, upload_to='product_videos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accessibility_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
