# Generated by Django 5.2.4 on 2026-03-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_voice_2fa_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collab_recs',
            field=models.CharField(blank=True, default='', help_text='Comma-separated product IDs (auto-generated by build_collab_filter)', max_length=200),
        ),
    ]
